//! Compaction rules without IO (Node `compact/prompt.ts`, `manual.ts`,
//! `rounds.ts`, `compact-selection.ts`, `turn-loop-state.ts`). Spec rust-m7-compact.
use crate::js_string::{substitute, trim};
use regex::Regex;
use serde_json::Value;
use std::sync::OnceLock;

/// Node `MAX_OUTPUT_TOKENS_FOR_SUMMARY`.
pub const MAX_SUMMARY_OUTPUT: usize = 20_000;
/// Node `COMPACT_TOOL_KEEP_MAX_COUNT`: more tools than this are not sent.
pub const MAX_SUMMARY_TOOLS: usize = 100;
/// Node `AUTO_COMPACT_MAX_ATTEMPTS`.
pub const AUTO_ATTEMPTS: u32 = 3;
/// Node `MAX_CONSECUTIVE_AUTOCOMPACT_FAILURES`.
pub const MAX_CONSECUTIVE_FAILURES: u32 = 3;
const RAPID_REFILL_TOOL_TURNS: u32 = 3;
const MAX_RAPID_REFILLS: u32 = 3;
pub const TOOL_USE_DENIED: &str = "Tool use is not allowed during compaction";
pub const EMPTY_SUMMARY: &str = "Failed to generate compact summary";
/// Node `COMPACT_PROMPT_TOO_LONG_USER_MESSAGE`.
pub const TOO_LONG: &str = "Conversation too long to compact automatically. Try /compact again after narrowing the active context.";
/// The first line of Node's summary message (new summaries are sent verbatim).
pub const SUMMARY_HEADER: &str = "This session is being continued from a previous conversation";

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct Templates {
    compact: String,
    compact_instructions: String,
    compact_summary: String,
}

/// Node's prompt and message, generated by `scripts/generate-zcode-cli-rust-prompt.mjs`.
fn templates() -> &'static Templates {
    static TEMPLATES: OnceLock<Templates> = OnceLock::new();
    TEMPLATES.get_or_init(|| {
        serde_json::from_str(include_str!("prompt_templates.json")).expect("compact templates")
    })
}

/// Node `buildCompactPrompt`: custom instructions are added when not blank.
pub fn prompt(custom: Option<&str>) -> String {
    match custom.filter(|c| !c.trim().is_empty()) {
        Some(custom) => {
            templates()
                .compact_instructions
                .replacen("{zcode_compact_instructions}", custom, 1)
        }
        None => templates().compact.clone(),
    }
}

fn pattern(cell: &'static OnceLock<Regex>, source: &str) -> &'static Regex {
    cell.get_or_init(|| Regex::new(source).expect("valid pattern"))
}

/// Node `formatCompactSummary`.
pub fn format_summary(text: &str) -> String {
    static ANALYSIS: OnceLock<Regex> = OnceLock::new();
    static SUMMARY: OnceLock<Regex> = OnceLock::new();
    static BLANKS: OnceLock<Regex> = OnceLock::new();
    let mut formatted = trim(text).to_owned();
    if formatted.is_empty() {
        return formatted;
    }
    formatted = pattern(&ANALYSIS, r"<analysis>[\s\S]*?</analysis>")
        .replace(&formatted, regex::NoExpand(""))
        .into_owned();
    let summary = pattern(&SUMMARY, r"<summary>([\s\S]*?)</summary>");
    if let Some(found) = summary.captures(&formatted) {
        // Node 用字符串替换，替换串里的 `$&`、`$1` 等按 JS 规则展开（保留 Node 行为）。
        let range = found.get(0).unwrap().range();
        let body = format!("Summary:\n{}", trim(&found[1]));
        let parts = (
            &formatted[..range.start],
            &found[0],
            &formatted[range.end..],
        );
        let body = substitute(&body, parts, &[Some(&found[1])]);
        formatted = format!("{}{body}{}", parts.0, parts.2);
    }
    let formatted = pattern(&BLANKS, r"\n\n+").replace_all(&formatted, regex::NoExpand("\n\n"));
    trim(&formatted).to_owned()
}

/// Node `buildCompactSummaryMessage(summary, {suppressFollowup: true})`.
pub fn summary_message(summary: &str) -> String {
    let (head, tail) = templates()
        .compact_summary
        .split_once("{zcode_compact_summary}")
        .expect("summary placeholder");
    format!("{head}{}{tail}", format_summary(summary))
}

/// Whether each entry is an assistant message; the summary is a leading user entry.
pub(crate) fn assistant_roles(messages: &[Value], summary: bool) -> Vec<bool> {
    let mut roles = Vec::with_capacity(messages.len() + 1);
    if summary {
        roles.push(false);
    }
    roles.extend(messages.iter().map(|m| m["role"] == "assistant"));
    roles
}

/// Node `groupByAssistantStartedRounds`: a group starts at the first entry
/// and at every later assistant message.
pub(crate) fn group_starts(assistant: &[bool]) -> Vec<usize> {
    (0..assistant.len())
        .filter(|i| *i == 0 || assistant[*i])
        .collect()
}

/// Node `hasEnoughRuntimeEntriesToCompact`.
pub(crate) fn enough(assistant: &[bool]) -> bool {
    group_starts(assistant).len() >= 2 && assistant.contains(&true)
}

/// A selection: `messages[..split]` is summarized, the last `preserved` groups stay.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Plan {
    pub split: usize,
    pub preserved: usize,
}

/// Node `selectCompactEntries` with `minimumGroupsToPreserve`, `None` when the
/// summarized part cannot be compacted. `summary`: a summary precedes `messages`.
pub fn plan(messages: &[Value], summary: bool, manual: bool, minimum: usize) -> Option<Plan> {
    let roles = assistant_roles(messages, summary);
    let starts = group_starts(&roles);
    let total = starts.len();
    let preserved = if manual || total < 2 {
        0
    } else {
        minimum.max(1).min(total - 1)
    };
    let end = if preserved > 0 {
        starts[total - preserved]
    } else {
        roles.len()
    };
    enough(&roles[..end]).then(|| Plan {
        split: end - usize::from(summary),
        preserved,
    })
}

/// The end in `messages` of the summarized part (see [`plan`]).
pub fn select(messages: &[Value], summary: bool, manual: bool) -> Option<usize> {
    plan(messages, summary, manual, 0).map(|p| p.split)
}

/// Node `CompactLoopTracking` of one turn.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct RapidRefill {
    /// `None` until the turn compacted once.
    tracking: Option<(u32, u32)>,
}

impl RapidRefill {
    /// Node `evaluateRapidRefill`: the next consecutive count and whether it blocks.
    pub fn evaluate(&self) -> (u32, bool) {
        let consecutive = match self.tracking {
            Some((turns, consecutive)) if turns < RAPID_REFILL_TOOL_TURNS => consecutive + 1,
            _ => 0,
        };
        (consecutive, consecutive >= MAX_RAPID_REFILLS)
    }

    /// Node `recordCompactSuccess`.
    pub fn compacted(&mut self, consecutive: u32) {
        self.tracking = Some((0, consecutive));
    }

    /// Node `recordCompletedToolBatch`.
    pub fn tool_batch(&mut self) {
        if let Some((turns, _)) = &mut self.tracking {
            *turns += 1;
        }
    }
}

/// Node `createCompactRapidRefillError` text.
pub fn rapid_refill_error() -> String {
    format!(
        "Autocompact stopped because the context refilled within fewer than {RAPID_REFILL_TOOL_TURNS} tool turns after compaction {MAX_RAPID_REFILLS} times in a row. A file or tool output may be too large. Read it in smaller chunks, or start a new session."
    )
}

#[cfg(test)]
#[path = "compact_tests.rs"]
mod tests;
