// ZCodium 下游修改，契约/存储/安全边界适配，来源及许可见 Rust 根 NOTICE.md
pub mod agent_profile;
pub mod attachment_upload;
pub mod background;
pub mod claude_import;
pub mod compact;
pub mod compact_ptl;
pub mod config;
pub mod context;
pub mod delivery;
pub mod edit_match;
pub mod execution;
pub mod file_checkpoint;
pub mod goal;
pub mod goal_verdict;
pub mod history;
pub mod history_cold;
pub mod hooks;
pub mod js_json;
pub mod js_string;
pub mod json_order;
mod json_size;
pub mod legacy_attachments;
pub mod legacy_goal;
pub mod legacy_input_params;
pub mod legacy_params;
pub mod legacy_snapshot;
pub mod legacy_stream;
pub mod local_ttft;
pub mod model;
pub mod model_anomaly;
pub mod node_history;
pub mod node_ids;
pub mod node_journal;
pub mod node_rows;
pub mod option_map;
pub mod path_names;
pub mod permission;
pub mod persisted_output;
pub mod plan_mode;
pub mod plugin_reference;
pub mod prompt;
pub mod prompt_env;
pub mod question;
mod question_answer;
pub mod read_pdf;
pub mod result_budget;
pub mod row_page;
pub mod session;
pub mod session_debug;
pub mod session_listing;
mod session_memory;
pub mod session_projection;
mod session_recovery;
pub mod session_runtime;
pub mod session_title;
pub mod shared_context;
pub mod shared_import;
pub mod skills;
pub mod stream_recovery;
pub mod subagent;
mod subagent_outcome;
mod subagent_page;
pub mod subagent_query;
mod subagent_row;
pub mod telemetry;
pub mod todo;
pub mod tool_input;
pub mod topic_log;
pub mod usage;
pub mod web;
pub mod workspace_identity;
pub mod zod;

pub const MAX_REQUEST_BYTES: usize = 1024 * 1024;
pub const MAX_TEXT_BYTES: usize = 256 * 1024;
pub const MAX_TOOL_BYTES: usize = 64 * 1024;
pub const MAX_QUEUE: usize = 32;
