//! Parity with the Node hook modules (`fixtures/hooks.json`, generated by
//! `scripts/zcode-cli-rust-hooks-fixtures.mjs`).
use super::decision::{RequestAnswer, apply_pre_tool, request_answer, should_continue};
use super::output::{Callback, Diagnostics, Exec, RunResult, callback};
use super::*;
use crate::permission::{Behavior, Decision};
use serde_json::{Value, json};

pub(super) fn fixtures() -> Value {
    serde_json::from_str(include_str!("../../fixtures/hooks.json")).unwrap()
}

fn text(value: &Value) -> Option<&str> {
    value.as_str()
}

#[test]
fn inputs_and_stdin_match_node() {
    let f = fixtures();
    let cases = f["inputs"].as_array().unwrap();
    let base = |mode, trace, turn| input::Base {
        agent_name: None,
        cwd: "/work",
        mode,
        session_id: "session-1",
        timestamp: "2026-01-01T00:00:00.000Z",
        trace_id: trace,
        turn_id: Some(turn),
    };
    let runtime = input::Base {
        agent_name: Some("main"),
        ..base("build", "trace-1", "turn-1")
    };
    let call = |id, name, args| input::Call {
        id,
        name,
        input: args,
    };
    let ls = json!({"command":"ls"});
    let rm = json!({"command":"rm x"});
    let empty = json!({});
    let attachments = [
        input::Attachment {
            kind: "file",
            path: Some("/a.txt"),
            inline: None,
        },
        input::Attachment {
            kind: "image",
            path: None,
            inline: Some(4),
        },
        input::Attachment {
            kind: "file",
            path: None,
            inline: None,
        },
    ];
    let long = Value::from("x".repeat(4001));
    let built = [
        input::pre_tool_use(
            &base("build", "trace-1", "turn-1"),
            &call("call-1", "Bash", &ls),
            "low",
            Some("none"),
        ),
        input::pre_tool_use(
            &base("yolo", "t", "turn-deps"),
            &call("c2", "Agent", &empty),
            "high",
            None,
        ),
        input::permission_request(
            &base("build", "trace-1", "turn-1"),
            &call("call-1", "Bash", &rm),
            "Tool Bash requires approval",
            "perm_1",
            "high",
            Some("system"),
        ),
        input::permission_request(
            &base("edit", "trace-1", "turn-1"),
            &call("c3", "ApplyPatch", &empty),
            "Needs approval",
            "perm_2",
            "high",
            Some("system"),
        ),
        input::post_tool_use(
            &base("edit", "trace-1", "turn-1"),
            &call("call-1", "Bash", &ls),
            &json!({"exitCode":0,"stdout":"a\n"}),
            None,
        ),
        input::post_tool_use(
            &base("edit", "trace-1", "turn-1"),
            &call("call-1", "Bash", &empty),
            &long,
            Some("/artifacts/out.txt"),
        ),
        input::post_tool_use_failure(
            &base("edit", "trace-1", "turn-1"),
            &call("call-1", "Bash", &ls),
            "boom",
            "Error",
        ),
        input::post_tool_use_failure(
            &base("edit", "trace-1", "turn-1"),
            &call("call-1", "Bash", &empty),
            "Cancelled",
            "tool_cancelled",
        ),
        input::session_start(&runtime, Some("zai/glm-4.6"), "startup"),
        input::session_start(&runtime, None, "resume"),
        input::user_prompt_submit(&runtime, "hello", input::attachments_summary(&[])),
        input::user_prompt_submit(
            &runtime,
            "see files",
            input::attachments_summary(&attachments),
        ),
        input::stop(&runtime, "done", 2, false),
        input::stop(&runtime, &"y".repeat(4005), 0, true),
    ];
    assert_eq!(built.len(), cases.len());
    for (input, case) in built.iter().zip(cases) {
        // stdin 逐字比较：顶层键序与 Node 一致（嵌套对象按 serde 顺序，此处用例已有序）。
        assert_eq!(input.to_string(), case["input"].to_string());
        assert_eq!(
            input::stdin(input, "<transcript>"),
            text(&case["stdin"]).unwrap()
        );
        assert_eq!(input::transcript(input), text(&case["transcript"]).unwrap());
        let values: Vec<String> = match input["toolName"].as_str() {
            Some(tool) => tool_match_values(tool),
            None => input["source"]
                .as_str()
                .map(|s| vec![s.to_owned()])
                .unwrap_or_default(),
        };
        assert_eq!(json!(values), case["values"]);
    }
}

#[test]
fn matchers_follow_js_regexp() {
    for case in fixtures()["matchers"].as_array().unwrap() {
        let values: Vec<String> = serde_json::from_value(case[1].clone()).unwrap();
        assert_eq!(matches(case[0].as_str(), &values), case[2], "{case}");
    }
}

/// The Node callback result shape for one Rust callback.
fn node_callback(result: &Callback) -> Value {
    let d = &result.diagnostics;
    if *d == Diagnostics::default() {
        return result.output.clone().unwrap_or(Value::Null);
    }
    let mut diagnostics = json!({});
    for (key, value) in [
        ("errorMessage", &d.error_message),
        ("stderrPreview", &d.stderr_preview),
        ("stdoutPreview", &d.stdout_preview),
    ] {
        if let Some(value) = value {
            diagnostics[key] = value.clone().into();
        }
    }
    let mut out = json!({"kind":"hookCallbackResult"});
    if let Some(output) = &result.output {
        out["output"] = output.clone();
    }
    out["diagnostics"] = diagnostics;
    out
}

#[test]
fn process_results_match_node() {
    for case in fixtures()["callbacks"].as_array().unwrap() {
        let exec = Exec {
            status: case["status"].as_str().unwrap().into(),
            exit_code: case["exitCode"].as_i64().map(|c| c as i32),
            stdout: case["stdout"].as_str().unwrap().into(),
            stderr: case["stderr"].as_str().unwrap().into(),
            error: case["error"].as_str().map(str::to_owned),
        };
        let event = HookEvent::parse(case["event"].as_str().unwrap()).unwrap();
        match (callback(event, &exec), case.get("failure")) {
            (Ok(result), None) => assert_eq!(node_callback(&result), case["output"], "{case}"),
            (Err(failure), Some(expected)) => {
                let message = expected["cause"].as_str().or(expected["message"].as_str());
                assert_eq!(failure.message, message.unwrap(), "{case}");
                assert_eq!(failure.code, expected["code"].as_str(), "{case}");
            }
            (got, _) => panic!("{case}: {got:?}"),
        }
    }
}

/// A Node `HookRunResult` object as the Rust struct.
fn run_result(value: &Value) -> RunResult {
    let behavior = |name: &str| serde_json::from_value::<Behavior>(json!(name)).ok();
    RunResult {
        additional_contexts: serde_json::from_value(value["additionalContexts"].clone()).unwrap(),
        block_requested: value["blockRequested"] == true,
        decision_reason: value["hookPermissionDecisionReason"]
            .as_str()
            .map(str::to_owned),
        behavior: value["permissionBehavior"].as_str().and_then(behavior),
        request_decision: value.get("permissionRequestResult").cloned(),
        prevent_continuation: value["preventContinuation"] == true,
        stop_should_continue: value["stopShouldContinue"] == true,
        stop_reason: value["stopReason"].as_str().map(str::to_owned),
        updated_input: value.get("updatedInput").cloned(),
    }
}

#[test]
fn permission_request_answers_match_node() {
    for case in fixtures()["permission"].as_array().unwrap() {
        let answer = match request_answer(&run_result(&case["result"])) {
            None => Value::Null,
            Some(RequestAnswer::Deny(reason)) => json!({"decision":"deny","reason":reason}),
            Some(RequestAnswer::Allow(updates)) => {
                let mut out = json!({"decision":"allow"});
                if let Some(updates) = updates {
                    out["permissionUpdates"] = updates;
                }
                out["reason"] = output_reason(false).into();
                out
            }
            Some(RequestAnswer::Modify { input, updates }) => {
                let mut out = json!({"decision":"modify","modifiedInput":input});
                if let Some(updates) = updates {
                    out["permissionUpdates"] = updates;
                }
                out["reason"] = output_reason(true).into();
                out
            }
        };
        assert_eq!(answer, case["answer"], "{case}");
    }
}

fn output_reason(modified: bool) -> &'static str {
    if modified {
        super::decision::MODIFIED_BY_HOOK
    } else {
        super::decision::ALLOWED_BY_HOOK
    }
}

#[test]
fn pre_tool_use_overrides_match_node() {
    for case in fixtures()["preDecisions"].as_array().unwrap() {
        let d = &case["decision"];
        let mut decision = Decision {
            behavior: serde_json::from_value(d["decision"].clone()).unwrap(),
            rule_id: "r",
            reason: d["reason"].as_str().unwrap().into(),
            risk_level: "low".into(),
            side_effect_scope: "none".into(),
            always_ask: d["alwaysAsk"] == true,
        };
        let hook = RunResult {
            behavior: case["behavior"]
                .as_str()
                .and_then(|b| serde_json::from_value(json!(b)).ok()),
            decision_reason: case["reason"].as_str().map(str::to_owned),
            ..RunResult::default()
        };
        apply_pre_tool(&mut decision, &hook);
        let got = json!({"decision":decision.behavior,"reason":decision.reason,"ruleId":decision.rule_id});
        assert_eq!(got, case["result"], "{case}");
    }
}

#[test]
fn texts_match_node() {
    let f = fixtures();
    let t = &f["texts"];
    assert_eq!(
        display::tool_contexts(&["one".into(), "two\nlines".into()]),
        t["toolContexts"]
    );
    for case in t["lifecycle"].as_array().unwrap() {
        let contexts: Vec<String> = case["contexts"]
            .as_array()
            .unwrap()
            .iter()
            .map(|c| match c.as_str().unwrap().strip_prefix("z*") {
                Some(n) => "z".repeat(n.parse().unwrap()),
                None => c.as_str().unwrap().into(),
            })
            .collect();
        let event = HookEvent::parse(case["event"].as_str().unwrap()).unwrap();
        assert_eq!(
            json!(display::lifecycle_body(event, &contexts)),
            case["body"]
        );
    }
    for case in t["previews"].as_array().unwrap() {
        let value = match case[0].as_str().and_then(|s| s.split_once('*')) {
            Some((c, n)) => Value::from(c.repeat(n.parse().unwrap())),
            None => case[0].clone(),
        };
        assert_eq!(input::preview(&value), case[1].as_str().unwrap());
    }
    for case in t["stopContinue"].as_array().unwrap() {
        let result = run_result(&case[0]);
        assert_eq!(
            should_continue(&result, case[1].as_u64().unwrap() as usize),
            case[2]
        );
    }
    for case in t["sanitize"].as_array().unwrap() {
        assert_eq!(
            display::sanitize(case[0].as_str().unwrap()),
            case[1].as_str().unwrap(),
            "{case}"
        );
    }
    for case in t["descriptors"].as_array().unwrap() {
        let hook = &case[0];
        let plugin = hook.get("plugin").map(|p| Plugin {
            id: p["id"].as_str().unwrap().into(),
            name: p["name"].as_str().unwrap().into(),
            root_path: p["rootPath"].as_str().unwrap().into(),
            data_path: p["dataPath"].as_str().unwrap().into(),
            source_path: p["sourcePath"].as_str().map(str::to_owned),
        });
        let registration = Registration {
            event: HookEvent::PreToolUse,
            matcher: None,
            program: program(hook).unwrap(),
            source: "config.PreToolUse.0.0".into(),
            source_kind: match (plugin.is_some(), hook["source"]["kind"].as_str()) {
                (true, _) => SourceKind::Plugin,
                (_, Some("project")) => SourceKind::Project,
                _ => SourceKind::User,
            },
            source_path: hook["source"]["path"].as_str().map(str::to_owned),
            plugin,
            status_message: hook["statusMessage"].as_str().map(str::to_owned),
            timeout_ms: case[1].as_u64().unwrap(),
            max_output_bytes: 32768,
            review: None,
        };
        let got = display::descriptor(&registration, &json!({"sessionId":"s-1","cwd":"/w"}));
        assert_eq!(got.to_string(), case[2].to_string());
    }
}
