//! Replays `fixtures/node-db.json` (Node's repositories on fixed operations,
//! generated by `scripts/zcode-cli-rust-node-db-fixtures.mjs`) and requires
//! byte-identical tables and decoded reads.
use super::json::stringify;
use super::*;
use rusqlite::Connection;
use serde_json::{Value, json};
use zcode_cli_domain::node_ids;

fn fixture() -> Value {
    serde_json::from_str(include_str!("../../fixtures/node-db.json")).unwrap()
}

fn text(v: &Value) -> Option<String> {
    v.as_str().map(str::to_owned)
}

fn patch<T: Clone>(v: &Value, map: impl Fn(&Value) -> T) -> sessions::Patch<T> {
    if v.is_null() {
        sessions::Patch::Keep
    } else {
        sessions::Patch::Set(map(v))
    }
}

fn create(input: &Value) -> sessions::Create {
    sessions::Create {
        id: text(&input["id"]).unwrap(),
        project_id: text(&input["projectID"]).unwrap(),
        workspace_id: text(&input["workspaceID"]),
        parent_id: text(&input["parentID"]),
        trace_id: text(&input["traceID"]),
        task_type: text(&input["taskType"]),
        slug: text(&input["slug"]).unwrap(),
        directory: text(&input["directory"]).unwrap(),
        path: text(&input["path"]),
        title: text(&input["title"]).unwrap(),
        title_source: text(&input["titleSource"]),
        title_message_id: text(&input["titleMessageID"]),
        version: text(&input["version"]).unwrap(),
        share_url: None,
        permission: Some(input["permission"].clone()).filter(|p| !p.is_null()),
        time_created: None,
        time_updated: None,
    }
}

fn update(input: &Value) -> sessions::Update {
    sessions::Update {
        id: text(&input["id"]).unwrap(),
        title: text(&input["title"]),
        title_source: text(&input["titleSource"]),
        expected_title_sources: input["expectedTitleSources"]
            .as_array()
            .map(|a| a.iter().filter_map(text).collect())
            .unwrap_or_default(),
        time_archived: patch(&input["timeArchived"], |v| v.as_i64().unwrap()),
        ..Default::default()
    }
}

fn target_id(conn: &Connection, session: &str) -> String {
    targets::read(conn, session).unwrap().unwrap().target_id
}

fn apply(conn: &Connection, o: &Value, clock: &mut i64) {
    if let Some(now) = o["now"].as_i64() {
        *clock = now;
    }
    let now = *clock;
    let session = o["sessionID"].as_str().unwrap_or("");
    let copy = o["copyFrom"].as_object().map(|c| messages::CopyFrom {
        session_id: c["sessionID"].as_str().unwrap(),
        id: c["id"].as_str().unwrap(),
    });
    match o["op"].as_str().unwrap() {
        "exec" => conn.execute_batch(o["sql"].as_str().unwrap()).unwrap(),
        "createSession" => drop(sessions::create(conn, &create(&o["input"]), now).unwrap()),
        "updateSession" => drop(sessions::update(conn, &update(&o["input"]), now).unwrap()),
        "setRevert" => {
            drop(sessions::set_revert(conn, session, o["revert"].clone(), None, now).unwrap())
        }
        "saveMessage" => messages::save_message(conn, &o["info"], copy, now).unwrap(),
        "savePart" => messages::save_part(conn, &o["part"], copy, now).unwrap(),
        "removeMessage" => {
            messages::remove_message(conn, session, o["messageID"].as_str().unwrap()).unwrap()
        }
        "saveEntry" => {
            let e = &o["entry"];
            entries::save(
                conn,
                &entries::Entry {
                    id: text(&e["id"]).unwrap(),
                    session_id: text(&e["sessionID"]).unwrap(),
                    kind: text(&e["type"]).unwrap(),
                    time_created: e["time"]["created"].as_i64().unwrap(),
                    time_updated: e["time"]["updated"].as_i64().unwrap(),
                    data: e["data"].clone(),
                    touch_session: e["touchSession"] != false,
                },
            )
            .unwrap();
        }
        "saveInput" => {
            let i = &o["input"];
            let field = |k: &str| i[k].as_str().unwrap();
            inputs::save(
                conn,
                field("id"),
                field("sessionID"),
                field("kind"),
                field("delivery"),
                &i["payload"],
                now,
            )
            .unwrap();
        }
        "updateInputs" => {
            let patches: Vec<inputs::Patch> = o["updates"]
                .as_array()
                .unwrap()
                .iter()
                .map(|u| inputs::Patch {
                    id: text(&u["id"]).unwrap(),
                    delivery: text(&u["delivery"]),
                    intent: Some(u["intent"].clone()).filter(|v| !v.is_null()),
                    text: text(&u["text"]),
                    queue_position: u["queuePosition"].as_i64(),
                })
                .collect();
            inputs::update(conn, session, &patches, now).unwrap();
        }
        "promoteInput" => inputs::promote(
            conn,
            o["id"].as_str().unwrap(),
            session,
            &o["message"],
            o["parts"].as_array().unwrap(),
            now,
        )
        .unwrap(),
        "settleInput" => inputs::settle(
            conn,
            o["id"].as_str().unwrap(),
            session,
            o["status"].as_str().unwrap(),
            o["reason"].as_str(),
            now,
        )
        .unwrap(),
        "markPromoted" => inputs::mark_promoted(
            conn,
            o["id"].as_str().unwrap(),
            session,
            o["messageID"].as_str().unwrap(),
            now,
        )
        .unwrap(),
        "updateTodos" => {
            let list: Vec<todos::Todo> = o["todos"]
                .as_array()
                .unwrap()
                .iter()
                .map(|t| todos::Todo {
                    content: text(&t["content"]).unwrap(),
                    status: text(&t["status"]).unwrap(),
                    priority: text(&t["priority"]).unwrap(),
                })
                .collect();
            todos::update(conn, session, &list, now).unwrap();
        }
        "setTarget" => drop(
            targets::set(
                conn,
                session,
                &node_ids::target_id(now as u64, o["uuid"].as_str().unwrap()),
                o["objective"].as_str().unwrap(),
                o["status"].as_str().unwrap(),
                o["tokenBudget"].as_i64(),
                now,
            )
            .unwrap(),
        ),
        "startTargetRun" => drop(
            targets::start_run(
                conn,
                session,
                &target_id(conn, session),
                o["inputID"].as_str().unwrap(),
                o["startedAtMs"].as_i64().unwrap(),
            )
            .unwrap(),
        ),
        "heartbeatTargetRun" => drop(
            targets::heartbeat_run(
                conn,
                session,
                &target_id(conn, session),
                o["inputID"].as_str().unwrap(),
                o["seenAtMs"].as_i64().unwrap(),
            )
            .unwrap(),
        ),
        "finishTargetRun" => drop(
            targets::finish_run(
                conn,
                session,
                &target_id(conn, session),
                o["inputID"].as_str().unwrap(),
                o["endedAtMs"].as_i64().unwrap(),
                o["status"].as_str(),
                o["tokensUsedDelta"].as_i64().unwrap_or(0),
            )
            .unwrap(),
        ),
        "recoverTargetRun" => drop(targets::recover_interrupted_run(conn, session).unwrap()),
        "updateTargetStatus" => {
            drop(targets::update_status(conn, session, o["status"].as_str().unwrap(), now).unwrap())
        }
        "updateTargetSummaryTitle" => drop(
            targets::update_summary_title(
                conn,
                session,
                &target_id(conn, session),
                o["summaryTitle"].as_str().unwrap(),
                now,
            )
            .unwrap(),
        ),
        "accountTargetUsage" => drop(
            targets::account_usage(
                conn,
                session,
                &target_id(conn, session),
                o["tokensUsedDelta"].as_i64().unwrap_or(0),
                o["timeUsedSecondsDelta"].as_i64().unwrap_or(0),
                now,
            )
            .unwrap(),
        ),
        "savePermissionMode" => settings::save_project_permission_mode(
            conn,
            o["projectID"].as_str().unwrap(),
            o["mode"].as_str().unwrap(),
            now,
        )
        .unwrap(),
        "savePermission" => settings::save_project_permission(
            conn,
            o["projectID"].as_str().unwrap(),
            &o["permission"],
            now,
        )
        .unwrap(),
        "recordInputHistory" => {
            let i = &o["input"];
            let id = node_ids::input_history_id(now as u64, o["uuid"].as_str().unwrap());
            drop(
                input_history::record(
                    conn,
                    &id,
                    i["projectID"].as_str().unwrap(),
                    i["sessionID"].as_str(),
                    i["text"].as_str().unwrap(),
                    i.get("attachments"),
                    i["kind"].as_str().unwrap(),
                    i["time"]["created"].as_i64().unwrap_or(now),
                )
                .unwrap(),
            );
        }
        other => panic!("unknown op {other}"),
    }
}

fn dump(conn: &Connection, table: &str) -> Value {
    let mut statement = conn
        .prepare(&format!("select * from {table} order by rowid"))
        .unwrap();
    let columns = statement.column_count();
    let rows: Vec<Value> = statement
        .query_map([], |row| {
            Ok(Value::Array(
                (0..columns)
                    .map(|i| match row.get_ref(i).unwrap() {
                        rusqlite::types::ValueRef::Null => Value::Null,
                        rusqlite::types::ValueRef::Integer(v) => v.into(),
                        rusqlite::types::ValueRef::Real(v) => v.into(),
                        rusqlite::types::ValueRef::Text(t) => {
                            String::from_utf8_lossy(t).into_owned().into()
                        }
                        rusqlite::types::ValueRef::Blob(_) => panic!("blob"),
                    })
                    .collect(),
            ))
        })
        .unwrap()
        .collect::<rusqlite::Result<_>>()
        .unwrap();
    Value::Array(rows)
}

#[test]
fn node_repository_operations_produce_identical_rows() {
    let fixture = fixture();
    let dir = tempfile::tempdir().unwrap();
    let conn = open::open(
        &dir.path().join("db.sqlite"),
        open::MIGRATION_LOCK_WAIT,
        &mut |_| {},
    )
    .unwrap();
    let mut clock = 0;
    for o in fixture["operations"].as_array().unwrap() {
        apply(&conn, o, &mut clock);
    }
    for (table, expected) in fixture["tables"].as_object().unwrap() {
        assert_eq!(
            stringify(&dump(&conn, table)),
            stringify(expected),
            "table {table}"
        );
    }

    let read = &fixture["read"];
    let messages: Vec<Value> = messages::messages(&conn, "sess_a")
        .unwrap()
        .into_iter()
        .map(|m| json!({"info": m.info, "parts": m.parts}))
        .collect();
    assert_eq!(
        stringify(&Value::Array(messages)),
        stringify(&read["messages"])
    );
    let entries: Vec<Value> = entries::list(&conn, "sess_a", None)
        .unwrap()
        .into_iter()
        .map(|e| {
            json!({"id": e.id, "sessionID": e.session_id, "type": e.kind,
                "time": {"created": e.time_created, "updated": e.time_updated}, "data": e.data})
        })
        .collect();
    assert_eq!(
        stringify(&Value::Array(entries)),
        stringify(&read["entries"])
    );
    let inputs: Vec<Value> = inputs::list(&conn, "sess_a", None)
        .unwrap()
        .into_iter()
        .map(|i| {
            let mut record = json!({"id": i.id, "sessionID": i.session_id, "kind": i.kind,
                "delivery": i.delivery, "payload": i.payload, "admittedSequence": i.admitted_sequence});
            if let Some(v) = i.promoted_sequence {
                record["promotedSequence"] = v.into();
            }
            if let Some(v) = i.promoted_message_id {
                record["promotedMessageID"] = v.into();
            }
            record["status"] = i.status.into();
            if let Some(v) = i.status_reason {
                record["statusReason"] = v.into();
            }
            record["time"] = json!({"created": i.time_created, "updated": i.time_updated});
            record
        })
        .collect();
    assert_eq!(stringify(&Value::Array(inputs)), stringify(&read["inputs"]));
    let list = sessions::list(
        &conn,
        &sessions::List {
            directory: Some("/w".into()),
            task_types: vec!["interactive".into(), "subagent_child".into()],
            ..Default::default()
        },
    )
    .unwrap();
    let ids: Vec<&str> = list.iter().map(|s| s.id.as_str()).collect();
    assert_eq!(json!(ids), read["list"]);
}
