//! Permission prompt options and texts (Node `bootstrap/src/permission-options.ts`,
//! `permission-suggestions.ts`, V4 projection in `product-projection.ts`) plus the
//! exported runtime tables (tool capabilities, WebFetch preapproved hosts).
use super::{Behavior, Rule, ToolCapability, Update};
use serde::Deserialize;
use serde_json::{Value, json};
use std::{collections::BTreeMap, sync::OnceLock};

#[derive(Deserialize)]
struct WebFetch {
    hosts: Vec<String>,
    #[serde(rename = "pathPrefixes")]
    path_prefixes: BTreeMap<String, Vec<String>>,
}

#[derive(Deserialize)]
struct Data {
    tools: BTreeMap<String, ToolCapability>,
    webfetch: WebFetch,
    texts: BTreeMap<String, String>,
}

/// Generated by `scripts/zcode-cli-rust-permission-fixtures.mjs` from Node.
fn data() -> &'static Data {
    static DATA: OnceLock<Data> = OnceLock::new();
    DATA.get_or_init(|| {
        serde_json::from_str(include_str!("../../schema/tool-permissions.json"))
            .expect("generated tool permission data")
    })
}

/// Static capability of a built-in tool as Node declares it.
pub fn tool_capability(name: &str) -> Option<&'static ToolCapability> {
    data().tools.get(name)
}

/// Node `PERMISSION_DENIED_BY_USER_CONTENT`.
pub fn denied_by_user() -> &'static str {
    &data().texts["deniedByUser"]
}

/// Node `buildPermissionDeniedContent`.
pub fn denied_content(feedback: Option<&str>) -> String {
    match feedback.map(str::trim).filter(|f| !f.is_empty()) {
        Some(feedback) => format!(
            "{} To tell you how to proceed, the user said:\n{feedback}",
            denied_by_user()
        ),
        None => denied_by_user().into(),
    }
}

/// Node `isWebFetchPreapprovedUrl`.
pub fn webfetch_preapproved(value: &str) -> bool {
    let Ok(url) = url::Url::parse(value) else {
        return false;
    };
    let host = url.host_str().unwrap_or("");
    let table = &data().webfetch;
    if table.hosts.iter().any(|h| h == host) {
        return true;
    }
    let Some(prefixes) = table.path_prefixes.get(host) else {
        return false;
    };
    let path = url.path();
    let lower = path.to_ascii_lowercase();
    // `/%(25)*(2f|5c|2e)/iu`：编码后的路径分隔符或点，拒绝前缀穿越。
    let encoded_separator = lower.match_indices('%').any(|(at, _)| {
        let mut rest = &lower[at + 1..];
        while let Some(next) = rest.strip_prefix("25") {
            rest = next;
        }
        rest.starts_with("2f") || rest.starts_with("5c") || rest.starts_with("2e")
    });
    !encoded_separator
        && prefixes.iter().any(|p| {
            path == p
                || path
                    .strip_prefix(p.as_str())
                    .is_some_and(|r| r.starts_with('/'))
        })
}

const RULE_INPUT_KEYS: [&str; 5] = ["command", "url", "file_path", "path", "pattern"];

fn rule_content(input: &Value) -> Option<String> {
    if let Some(input) = input.as_str() {
        return (!input.trim().is_empty()).then(|| input.into());
    }
    RULE_INPUT_KEYS.iter().find_map(|key| {
        input[*key]
            .as_str()
            .filter(|v| !v.trim().is_empty())
            .map(str::to_owned)
    })
}

const OFFICIAL_CUA_RULE_TOOL: &str = "zcode:permission-capability:official_cua";

/// Node `buildDefaultPermissionUpdates`.
pub fn default_updates(tool: &str, input: &Value, group: Option<&str>) -> Vec<Update> {
    let rule = match group {
        Some(_) => Rule {
            tool_name: OFFICIAL_CUA_RULE_TOOL.into(),
            rule_content: None,
        },
        None => Rule {
            tool_name: tool.into(),
            rule_content: rule_content(input),
        },
    };
    vec![Update {
        kind: "addRules".into(),
        behavior: Behavior::Allow,
        rules: vec![rule],
    }]
}

/// Node `buildProtocolPermissionOptions` (snake_case option ids, as the broker uses them).
pub fn protocol_options(
    tool: &str,
    input: &Value,
    suggested: &[Update],
    policy: Option<&str>,
) -> Vec<Value> {
    let updates = if suggested.is_empty() {
        default_updates(tool, input, None)
    } else {
        suggested.to_vec()
    };
    let cua = updates.iter().any(|u| {
        u.rules
            .iter()
            .any(|r| r.tool_name == OFFICIAL_CUA_RULE_TOOL)
    });
    let mut options = vec![
        json!({"kind":"allow_once","name":"Allow once","optionId":"allow_once",
        "response":{"decision":"allow","reason":"Approved once"}}),
    ];
    match policy {
        Some("no-always-allow") => {}
        Some("session-always-allow") => options.push(json!({
            "description":"Do not ask again for this tool in this session","kind":"allow_session",
            "name":"Always allow in this session","optionId":"allowSession",
            "response":{"decision":"allow","reason":"Approved for this session"}})),
        _ => options.push(json!({
            "description": if cua {"Do not ask again for official Computer Use tools in this project"} else {"Do not ask again for matching requests in this project"},
            "kind":"allow_always",
            "name": if cua {"Always allow Computer Use in this project"} else {"Always allow in this project"},
            "optionId":"allow_project",
            "response":{"decision":"allow","permissionUpdates":updates,"reason":"Approved for this project"}})),
    }
    options.push(json!({"kind":"deny","name":"Deny","optionId":"deny",
        "response":{"decision":"deny","reason":denied_by_user()}}));
    options
}

/// V4 pending-interaction options (Node `product-projection.ts` mapping).
pub fn v4_options(
    tool: &str,
    input: &Value,
    suggested: &[Update],
    policy: Option<&str>,
) -> Vec<Value> {
    let mut options: Vec<Value> = protocol_options(tool, input, suggested, policy)
        .into_iter()
        .map(|option| {
            let (id, kind) = match option["kind"].as_str() {
                Some("allow_once") => ("allowOnce".into(), "allowOnce"),
                Some("allow_always") => ("allowAlways".into(), "allowAlways"),
                Some("allow_session") => (option["optionId"].clone(), "allowAlways"),
                _ => (option["optionId"].clone(), "deny"),
            };
            json!({"optionId":id,"label":option["name"],"kind":kind,"response":option["response"]})
        })
        .collect();
    if matches!(tool, "CreateWorkflow" | "AmendWorkflow") {
        options.push(
            json!({"optionId":"workflowRefine","label":"Refine","kind":"custom",
            "response":{"decision":"deny","reason":"Denied"}}),
        );
    }
    options
}
